final List<Map<String, String>> languages = [
  {'code': 'ab', 'name': 'Abkhazian'},
  {'code': 'ace', 'name': 'Acehnese'},
  {'code': 'ach', 'name': 'Acoli'},
  {'code': 'af', 'name': 'Afrikaans'},
  {'code': 'ak', 'name': 'Akan'},
  {'code': 'alz', 'name': 'Alur'},
  {'code': 'am', 'name': 'Amharic'},
  {'code': 'ar', 'name': 'Arabic'},
  {'code': 'as', 'name': 'Assamese'},
  {'code': 'awa', 'name': 'Awadhi'},
  {'code': 'ay', 'name': 'Aymara'},
  {'code': 'az', 'name': 'Azerbaijani'},
  {'code': 'ba', 'name': 'Bashkir'},
  {'code': 'ban', 'name': 'Balinese'},
  {'code': 'bbc', 'name': 'Batak Toba'},
  {'code': 'be', 'name': 'Belarusian'},
  {'code': 'bem', 'name': 'Bemba'},
  {'code': 'bew', 'name': 'Betawi'},
  {'code': 'bg', 'name': 'Bulgarian'},
  {'code': 'bho', 'name': 'Bhojpuri'},
  {'code': 'bik', 'name': 'Bikol'},
  {'code': 'bm', 'name': 'Bambara'},
  {'code': 'bn', 'name': 'Bengali'},
  {'code': 'br', 'name': 'Breton'},
  {'code': 'bs', 'name': 'Bosnian'},
  {'code': 'bts', 'name': 'Batak Simalungun'},
  {'code': 'btx', 'name': 'Batak Karo'},
  {'code': 'bua', 'name': 'Buriat'},
  {'code': 'ca', 'name': 'Catalan'},
  {'code': 'ceb', 'name': 'Cebuano'},
  {'code': 'cgg', 'name': 'Chiga'},
  {'code': 'chm', 'name': 'Mari'},
  {'code': 'ckb', 'name': 'Central Kurdish'},
  {'code': 'cnh', 'name': 'Hakha Chin'},
  {'code': 'co', 'name': 'Corsican'},
  {'code': 'crh', 'name': 'Crimean Tatar'},
  {'code': 'crs', 'name': 'Seselwa Creole French'},
  {'code': 'cs', 'name': 'Czech'},
  {'code': 'cv', 'name': 'Chuvash'},
  {'code': 'cy', 'name': 'Welsh'},
  {'code': 'da', 'name': 'Danish'},
  {'code': 'de', 'name': 'German'},
  {'code': 'din', 'name': 'Dinka'},
  {'code': 'doi', 'name': 'Dogri'},
  {'code': 'dov', 'name': 'Dombe'},
  {'code': 'dv', 'name': 'Divehi'},
  {'code': 'dz', 'name': 'Dzongkha'},
  {'code': 'ee', 'name': 'Ewe'},
  {'code': 'el', 'name': 'Greek'},
  {'code': 'en', 'name': 'English'},
  {'code': 'eo', 'name': 'Esperanto'},
  {'code': 'es', 'name': 'Spanish'},
  {'code': 'et', 'name': 'Estonian'},
  {'code': 'eu', 'name': 'Basque'},
  {'code': 'fa', 'name': 'Persian'},
  {'code': 'ff', 'name': 'Fulah'},
  {'code': 'fi', 'name': 'Finnish'},
  {'code': 'fj', 'name': 'Fijian'},
  {'code': 'fr', 'name': 'French'},
  {'code': 'fy', 'name': 'Western Frisian'},
  {'code': 'ga', 'name': 'Irish'},
  {'code': 'gaa', 'name': 'Ga'},
  {'code': 'gd', 'name': 'Scottish Gaelic'},
  {'code': 'gl', 'name': 'Galician'},
  {'code': 'gn', 'name': 'Guarani'},
  {'code': 'gom', 'name': 'Goan Konkani'},
  {'code': 'gu', 'name': 'Gujarati'},
  {'code': 'ha', 'name': 'Hausa'},
  {'code': 'haw', 'name': 'Hawaiian'},
  {'code': 'he', 'name': 'Hebrew'},
  {'code': 'hi', 'name': 'Hindi'},
  {'code': 'hil', 'name': 'Hiligaynon'},
  {'code': 'hmn', 'name': 'Hmong'},
  {'code': 'hr', 'name': 'Croatian'},
  {'code': 'hrx', 'name': 'Hunsrik'},
  {'code': 'ht', 'name': 'Haitian Creole'},
  {'code': 'hu', 'name': 'Hungarian'},
  {'code': 'hy', 'name': 'Armenian'},
  {'code': 'id', 'name': 'Indonesian'},
  {'code': 'ig', 'name': 'Igbo'},
  {'code': 'ilo', 'name': 'Iloko'},
  {'code': 'is', 'name': 'Icelandic'},
  {'code': 'it', 'name': 'Italian'},
  {'code': 'iw', 'name': 'Hebrew'},
  {'code': 'ja', 'name': 'Japanese'},
  {'code': 'jv', 'name': 'Javanese'},
  {'code': 'jw', 'name': 'Javanese'},
  {'code': 'ka', 'name': 'Georgian'},
  {'code': 'kk', 'name': 'Kazakh'},
  {'code': 'km', 'name': 'Khmer'},
  {'code': 'kn', 'name': 'Kannada'},
  {'code': 'ko', 'name': 'Korean'},
  {'code': 'kri', 'name': 'Krio'},
  {'code': 'ktu', 'name': 'Kituba'},
  {'code': 'ku', 'name': 'Kurdish'},
  {'code': 'ky', 'name': 'Kyrgyz'},
  {'code': 'la', 'name': 'Latin'},
  {'code': 'lb', 'name': 'Luxembourgish'},
  {'code': 'lg', 'name': 'Ganda'},
  {'code': 'li', 'name': 'Limburgish'},
  {'code': 'lij', 'name': 'Ligurian'},
  {'code': 'lmo', 'name': 'Lombard'},
  {'code': 'ln', 'name': 'Lingala'},
  {'code': 'lo', 'name': 'Lao'},
  {'code': 'lt', 'name': 'Lithuanian'},
  {'code': 'ltg', 'name': 'Latgalian'},
  {'code': 'luo', 'name': 'Luo'},
  {'code': 'lus', 'name': 'Mizo'},
  {'code': 'lv', 'name': 'Latvian'},
  {'code': 'mai', 'name': 'Maithili'},
  {'code': 'mak', 'name': 'Makasar'},
  {'code': 'mg', 'name': 'Malagasy'},
  {'code': 'mi', 'name': 'Maori'},
  {'code': 'min', 'name': 'Minangkabau'},
  {'code': 'mk', 'name': 'Macedonian'},
  {'code': 'ml', 'name': 'Malayalam'},
  {'code': 'mn', 'name': 'Mongolian'},
  {'code': 'mni-Mtei', 'name': 'Meitei (Manipuri)'},
  {'code': 'mr', 'name': 'Marathi'},
  {'code': 'ms', 'name': 'Malay'},
  {'code': 'ms-Arab', 'name': 'Malay (Jawi)'},
  {'code': 'mt', 'name': 'Maltese'},
  {'code': 'my', 'name': 'Burmese'},
  {'code': 'ne', 'name': 'Nepali'},
  {'code': 'new', 'name': 'Newari'},
  {'code': 'nl', 'name': 'Dutch'},
  {'code': 'no', 'name': 'Norwegian'},
  {'code': 'nr', 'name': 'Southern Ndebele'},
  {'code': 'nso', 'name': 'Northern Sotho'},
  {'code': 'nus', 'name': 'Nuer'},
  {'code': 'ny', 'name': 'Nyanja'},
  {'code': 'oc', 'name': 'Occitan'},
  {'code': 'om', 'name': 'Oromo'},
  {'code': 'or', 'name': 'Odia'},
  {'code': 'pa', 'name': 'Punjabi'},
  {'code': 'pa-Arab', 'name': 'Punjabi (Shahmukhi)'},
  {'code': 'pag', 'name': 'Pangasinan'},
  {'code': 'pam', 'name': 'Pampanga'},
  {'code': 'pap', 'name': 'Papiamento'},
  {'code': 'pl', 'name': 'Polish'},
  {'code': 'ps', 'name': 'Pashto'},
  {'code': 'pt', 'name': 'Portuguese'},
  {'code': 'qu', 'name': 'Quechua'},
  {'code': 'rn', 'name': 'Rundi'},
  {'code': 'ro', 'name': 'Romanian'},
  {'code': 'rom', 'name': 'Romany'},
  {'code': 'ru', 'name': 'Russian'},
  {'code': 'rw', 'name': 'Kinyarwanda'},
  {'code': 'sa', 'name': 'Sanskrit'},
  {'code': 'scn', 'name': 'Sicilian'},
  {'code': 'sd', 'name': 'Sindhi'},
  {'code': 'sg', 'name': 'Sango'},
  {'code': 'shn', 'name': 'Shan'},
  {'code': 'si', 'name': 'Sinhala'},
  {'code': 'sk', 'name': 'Slovak'},
  {'code': 'sl', 'name': 'Slovenian'},
  {'code': 'sm', 'name': 'Samoan'},
  {'code': 'sn', 'name': 'Shona'},
  {'code': 'so', 'name': 'Somali'},
  {'code': 'sq', 'name': 'Albanian'},
  {'code': 'sr', 'name': 'Serbian'},
  {'code': 'ss', 'name': 'Swati'},
  {'code': 'st', 'name': 'Southern Sotho'},
  {'code': 'su', 'name': 'Sundanese'},
  {'code': 'sv', 'name': 'Swedish'},
  {'code': 'sw', 'name': 'Swahili'},
  {'code': 'szl', 'name': 'Silesian'},
  {'code': 'ta', 'name': 'Tamil'},
  {'code': 'te', 'name': 'Telugu'},
  {'code': 'tet', 'name': 'Tetum'},
  {'code': 'tg', 'name': 'Tajik'},
  {'code': 'th', 'name': 'Thai'},
  {'code': 'ti', 'name': 'Tigrinya'},
  {'code': 'tk', 'name': 'Turkmen'},
  {'code': 'tl', 'name': 'Tagalog'},
  {'code': 'tn', 'name': 'Tswana'},
  {'code': 'tr', 'name': 'Turkish'},
  {'code': 'ts', 'name': 'Tsonga'},
  {'code': 'tt', 'name': 'Tatar'},
  {'code': 'ug', 'name': 'Uyghur'},
  {'code': 'uk', 'name': 'Ukrainian'},
  {'code': 'ur', 'name': 'Urdu'},
  {'code': 'uz', 'name': 'Uzbek'},
  {'code': 'vi', 'name': 'Vietnamese'},
  {'code': 'xh', 'name': 'Xhosa'},
  {'code': 'yi', 'name': 'Yiddish'},
  {'code': 'yo', 'name': 'Yoruba'},
  {'code': 'yua', 'name': 'Yucatec Maya'},
  {'code': 'yue', 'name': 'Cantonese'},
  {'code': 'zh', 'name': 'Chinese'},
  {'code': 'zh-CN', 'name': 'Chinese (Simplified)'},
  {'code': 'zh-TW', 'name': 'Chinese (Traditional)'},
  {'code': 'zu', 'name': 'Zulu'},
];
