name: lacquer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_svg: ^2.0.17
    font_awesome_flutter: ^10.8.0
    percent_indicator: ^4.2.4
    #state management
    flutter_bloc: ^9.1.0
    equatable: ^2.0.7
    #RESTful API
    http: ^1.3.0
    dio: ^5.8.0+1
    #Local data storage
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    shared_preferences: ^2.5.2
    google_fonts: 6.2.1
    go_router: ^14.8.1
    google_sign_in: ^6.3.0
    flip_card: ^0.7.0
    intl: ^0.20.2
    image_picker: ^1.1.2
    camera: ^0.11.1
    path: ^1.9.1
    http_parser: ^4.1.2
  # Location and weather services
    geolocator: ^13.0.1
    geocoding: ^3.0.0
  # Image saving
    gal: ^2.3.0
    mime: ^2.0.0
    # QR code scanner
    qr_code_scanner_plus: ^2.0.10+1
    # Socket.IO for real-time chat
    socket_io_client: ^3.1.2
dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^2.0.1
    flutter_launcher_icons: ^0.14.3
    flutter_lints: ^5.0.0
    husky: ^0.1.7
    lint_staged: ^0.5.1
    commitlint_cli: ^0.8.1


flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/images/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package

lint_staged:
    "lib/**.dart": dart format write && dart fix --apply
