name: lacquer
description: "A new Flutter project."
publish_to: "none"

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_svg: ^2.0.17
    font_awesome_flutter: ^10.8.0
    #state management
    flutter_bloc: ^9.1.0
    equatable: ^2.0.7
    #RESTful API
    http: ^1.3.0
    dio: ^5.8.0+1
    #Local data storage
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    shared_preferences: ^2.5.2
    google_fonts: 6.2.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^2.0.1
    flutter_lints: ^5.0.0
    flutter_launcher_icons: ^0.14.3

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/app_icon.png"
    adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
    adaptive_icon_background: #F4B8E4

flutter:
    uses-material-design: true

    assets:
        - assets/icons/app_icon.png
        - assets/images/app_mascot.png

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
